# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX = "trusty64"
RAM = 2048

HOSTS = {
  "zk1" => "1",
  "zk2" => "2",
  "zk3" => "3",
}

DOMAIN = ".localhost"
NETWORK = "192.168.50."
NETMASK = "255.255.255.0"

Vagrant.configure(2) do |config|

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.synced_folder "../data", "/vagrant_data"

  HOSTS.each do | (name) |

    config.vm.define name do |machine|
      machine.vm.box     = BOX
      
      machine.vm.provider "virtualbox" do |vbox|
        vbox.memory = RAM
      end

      #machine.vm.hostname = machine_name + DOMAIN
      #machine.vm.network 'private_network', ip: name, netmask: NETMASK
    end
  end # HOSTS-each

  config.vm.provision "ansible" do |ansible|
    ansible.limit = 'all'
    ansible.groups = {
      "zookeeper" => ["zk1", "zk2", "zk3", ],
    }
    ansible.playbook = "zookeeper.yml"
  end
end
