# -*- mode: ruby -*-

BOX = "trusty64"
RAM = 2048

HOSTS = {
  "zk2" => "2",
  "zk3" => "3",
  "zk4" => "4",
}

DOMAIN = ".localhost"
NETWORK = "192.168.50."
NETMASK = "255.255.255.0"

Vagrant.configure(2) do |config|

  HOSTS.each do | (name, idx) |

    config.vm.define name do |machine|
      machine.vm.box     = BOX

      machine.vm.provider "virtualbox" do |vbox|
        vbox.memory = RAM
      end

      machine.vm.hostname = name + DOMAIN
      machine.vm.network 'private_network', ip: NETWORK + idx, netmask: NETMASK
    end
  end # HOSTS-each

  config.vm.provision "ansible" do |ansible|
    ansible.limit = 'all'
    ansible.groups = {
      "zookeeper" => ["zk1", "zk2", "zk3", ],
    }

    ansible.extra_vars = {
      network: NETWORK,
      cluster: HOSTS
    }
    ansible.playbook = "zookeeper.yml"
  end
end
